---
  - name: add mongodb repo key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: EA312927
    tags: install
  - name: add mongodb repo
    apt_repository:
      repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
      filename: mongodb
    tags: install
  - name: install mongodb
    apt:
      name: mongodb-org
      state: present
    tags: install
  - name: enable mongodb
    service:
      name: mongod
      enabled: yes
    tags: install
