---
  - name: Deploy app
    hosts: app
    tasks:
     - name: Fetch latest app code
       git:
        repo: 'https://github.com/express42/reddit.git'
        dest: '/home/appuser/reddit'
        version: monolith
       notify: restart puma
     - name: Install dependencies
       bundler:
        state: present
        chdir: /home/appuser/reddit
    handlers:
      - name: restart puma
        become: yes
        service: name=puma state=restarted

