---
  - name: Install ruby and bundler
    hosts: all
    become: yes
    tasks:
      - name: install ruby and bundler
        apt:
          name:
            - ruby-full
            - ruby-bundler
            - build-essential
          state: present
          update_cache: yes
