---
  - name: install mongodb
    hosts: all
    become: yes
    tasks:
      - name: add mongodb repo key
        apt_key:
          keyserver: hkp://keyserver.ubuntu.com:80
          id: EA312927
      - name: add mongodb repo
        apt_repository:
          repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
          filename: mongodb
      - name: install mongodb
        apt:
          name: mongodb-org
          state: present
      - name: enable mongodb
        service:
          name: mongod
          enabled: yes
