---
# tasks file for app
  - name: Configuring Puma`s environment variables
    notify: reload puma
    template:
      src: db_config.j2
      dest: /home/{{ deploy_user }}/db_config
      owner: "{{ deploy_user }}"
      group: "{{ deploy_user }}"

  - name: Copying Puma`s unit file
    notify: reload puma
    template:
      src: puma.service.j2
      dest: /etc/systemd/system/puma.service

  - name: Enable Puma
    service: name=puma enabled=yes
