---
  - name: Configure app
    hosts: app
    become: yes
    vars:
      db_host: 10.132.15.215
    tasks:
      - name: Configuring Puma`s environment variables
        template:
          src: templates/db_config.j2
          dest: /home/appuser/db_config

      - name: Copying Puma`s unit file
        notify: reload puma
        copy:
          src: files/puma.service
          dest: /etc/systemd/system/puma.service
          owner: appuser
          group: appuser

      - name: Enable Puma
        service: name=puma enabled=yes

    handlers:
      - name: reload puma
        service: name=puma state=reloaded
