---
 - name: all
   hosts: all
   vars:
     mongo_bind_ip: 0.0.0.0
     db_config: 10.132.0.2
   tasks:
     - name: Change MongoDB config file
       become: yes
       template:
         src: templates/mongod.conf.j2
         dest: /etc/mongod.conf
         mode: 0644
       tags: [ "db-tag" ]
       notify: restart mongod

     - name: Configuring Puma`s environment variables
       template:
         src: templates/db_config.j2
         dest: /home/appuser/db_config
       tags: [ "app-tag" ]
     - name: Copying Puma`s unit file
       become: yes
       copy:
         src: files/puma.service
         dest: /etc/systemd/system/puma.service
       tags: [ "app-tag" ]
       notify: reload puma
     - name: Enable Puma
       become: yes
       service: name=puma enabled=yes
       tags: [ "app-tag" ]
    handlers:
      - name: restart mongod
        become: yes
        service: name=mongod state=restarted
      - name: reload puma
        become: yes
        service: name=puma state=restarted
