# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
  end

  config.vm.define "dbserver" do |db|
      db.vm.box = "ubuntu/xenial64"
      db.vm.hostname = "dbserver"
      db.vm.network :private_network, ip: "10.10.10.10"

      db.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbooks/site.yml"
          ansible.groups = {
              "db" => [ "dbserver" ],
              "db:vars" => { "mongo_bind_ip" => "0.0.0.0" }
          }
      end
  end

  config.vm.define "appserver" do |app|
      app.vm.box = "ubuntu/xenial64"
      app.vm.hostname = "appserver"
      app.vm.network :private_network, ip: "10.10.10.20"

      app.vm.provision "ansible" do |ansible|
          require 'json'

          nginx_sites = {
              "default" => [
                  "listen 80",
                  'server_name "reddit"',
                  "location / { proxy_pass http://127.0.0.1:9292; }"
              ]
          }

          ansible.playbook = "playbooks/site.yml"
          ansible.groups = {
              "app" => [ "appserver" ],
              "app:vars" => {
                  "db_host" => "10.10.10.10",
                  "nginx_sites" => "#{nginx_sites.to_json}"
              }
          }
          ansible.extra_vars = {
              "deploy_user" => "vagrant"
          }
      end
  end

end
